name: GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            REPOSITORY_NAME: ${{ github.event.repository.name }}
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            # Install dependencies
            - run: yarn
            # Lint
            - run: yarn check
            # Build
            - run: yarn build
            # Deploy
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
